---
deployment:
  tasks:
    - source /home/lenauro/nodevenv/url-tracker.lenau.ro/20/bin/activate && cd /home/lenauro/url-tracker.lenau.ro
    - npm install
    - npm run build
    - touch ok.txt
    - touch tmp/restart.txt
    - rm tmp/restart.txt
